version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    ports:
      - "8080:8080"
    environment:
      JWT_SECRET: "3c855893-ce6d-490a-9b21-c215cee178c5"
      DB_URL: "jdbc:postgresql://postgres:5432/mydatabase"
      DB_USER: "myuser"
      DB_PASSWORD: "mypassword"
    depends_on:
      - postgres
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend: